$(document).ready(function(){
    $('.s-hover').hide();
    $('.g-bd').hover(
        function(){
            $('.s-hover').animate({width:'toggle'},350);
        },
        function(){
            $('.s-hover').animate({width:'toggle'},350);
        }
    );
});