$(document).ready(function(){
    $("#register").click(function(){
        $(this).addClass("active").siblings().removeClass("active");
        $(".register").show().siblings().hide();
    });
    $("#login").click(function(){
        $(this).addClass("active").siblings().removeClass("active");
        $(".login").show().siblings().hide();
    });
    $("#downApp").click(function(){
        $(this).addClass("active").siblings().removeClass("active");
        $(".download-app").show().siblings().hide();
    });
    $("#emailLogin").click(function(){
        $(this).hide();
        $("#phoneLogin").show();
        $("#telLogin-box").hide();
        $("#emailLogin-box").show();
    });
    $("#phoneLogin").click(function(){
        $(this).hide();
        $("#emailLogin").show();
        $("#emailLogin-box").hide();
        $("#telLogin-box").show();
    });
});